In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])


In [4]:
a.shape

(2, 2)

In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b = np.array([[5, 6]])

In [7]:
b

array([[5, 6]])

In [8]:
b.shape

(1, 2)

In [ ]:

np.concatenate((a, b), axis=0)
array([[1, 2],
       [3, 4],
       [5, 6]])
np.concatenate((a, b.T), axis=1)
array([[1, 2, 5],
       [3, 4, 6]])
np.concatenate((a, b), axis=None)
array([1, 2, 3, 4, 5, 6])