In [1]:
# https://stackoverflow.com/questions/61339532/get-predictions-for-all-users-with-surprise-svdpp-algorithm
from surprise import SVD
import pandas as pd
import numpy as np
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split
from surprise import Dataset
from surprise import Reader

In [2]:
ratings_data = pd.read_csv('./data/ratings.csv.zip')
books_metadata = pd.read_csv('./data/books.csv.zip')
ratings_data.head(10)

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4
5        1     2077       4
6        1     2487       4
7        1     2900       5
8        1     3662       4
9        1     3922       5

In [3]:
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(ratings_data[['user_id', 'book_id', 'rating']], reader)

In [4]:
#trainset = data.build_full_trainset()
trainset, testset = train_test_split(data, test_size=0.25)

In [5]:
algo = SVD()
algo.fit(trainset)

algo.predict(196, 302)

Prediction(uid=196, iid=302, r_ui=None, est=3.824637643686562, details={'was_impossible': False})

In [6]:
predictions = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions)

RMSE: 0.8457


0.8456594513660288

In [7]:
type(trainset._raw2inner_id_users)
users_dict=trainset._raw2inner_id_users

In [8]:
users_dict[196]

50770

In [9]:
trainset.to_raw_uid(44438)

48914

In [10]:
trainset.to_inner_uid(196)

50770

In [11]:
trainset.to_inner_iid(302)

9320

In [12]:
trainset.to_raw_iid(6996)

4726

In [13]:
trainset.to_inner_iid(302)

9320

In [14]:
items_dict=trainset._raw2inner_id_items

In [15]:
items_dict[302]

9320

In [16]:
algo.qi.shape

(10000, 100)

In [17]:
algo.pu.shape

(52809, 100)

In [18]:
algo.pu.transpose().shape

(100, 52809)

In [19]:
mat=np.dot(algo.qi,algo.pu.transpose())

In [20]:
mat.shape

(10000, 52809)

In [21]:
mat

array([[ 0.0328606 , -0.23649541,  0.04438997, ..., -0.14454349,
        -0.04085603,  0.08716504],
       [ 0.01984894, -0.20768016,  0.05231285, ...,  0.15121978,
         0.09041861, -0.10933611],
       [-0.08043432, -0.19624973,  0.13127568, ..., -0.2303272 ,
        -0.16858116,  0.0315671 ],
       ...,
       [ 0.13952133, -0.09061464, -0.06945457, ...,  0.18079002,
         0.179256  , -0.09393144],
       [-0.16740491,  0.16453608, -0.14065656, ...,  0.06407489,
         0.02844492,  0.02568933],
       [-0.22935499, -0.01324554, -0.00634005, ..., -0.03016311,
        -0.33775762,  0.25266811]])

In [22]:
algo.trainset.global_mean

3.8572449094615497

In [23]:
mat+algo.trainset.global_mean

array([[3.89010551, 3.6207495 , 3.90163488, ..., 3.71270142, 3.81638888,
        3.94440995],
       [3.87709385, 3.64956475, 3.90955776, ..., 4.00846469, 3.94766352,
        3.7479088 ],
       [3.77681058, 3.66099518, 3.98852059, ..., 3.62691771, 3.68866375,
        3.88881201],
       ...,
       [3.99676624, 3.76663027, 3.78779034, ..., 4.03803493, 4.03650091,
        3.76331347],
       [3.68984   , 4.02178099, 3.71658835, ..., 3.9213198 , 3.88568983,
        3.88293424],
       [3.62788992, 3.84399936, 3.85090486, ..., 3.8270818 , 3.51948729,
        4.10991302]])

In [24]:
shp=mat.shape
shp


(10000, 52809)

In [25]:
algo.bi

array([-0.18495313,  0.07077918, -0.1861568 , ...,  0.33084711,
       -0.04644233, -0.18104825])

In [26]:
algo.bi.shape

(10000,)

In [63]:
new=np.repeat(algo.bi,52777)

In [70]:
new.shape

(10000, 52777)

In [74]:
new.shape

(10000, 52777)

In [57]:
newmat=np.resize(new,(10000,2))

In [58]:
newmat

array([[ 0.14186459,  0.14186459],
       [ 0.08699358,  0.08699358],
       [ 0.19225928,  0.19225928],
       ...,
       [ 0.17713515,  0.17713515],
       [ 0.20022207,  0.20022207],
       [-0.3243696 , -0.3243696 ]])

In [37]:
algo.qi.shape

(10000, 100)

In [26]:
algo.trainset.global_mean + algo.bi[6996] + algo.bu[44438] + np.dot(algo.qi[6996], algo.pu[44438]) 

4.33167687631725

In [128]:
algo.trainset.global_mean

3.8565685703304418

In [131]:
len(users_dict)

52828

In [139]:
type(data)
ratings_data.shape
ratings_data['user_id'].nunique()


53424

In [140]:
ratings_data['user_id'].nunique()-len(users_dict)

596